<?xml version="1.0" encoding="utf-8"?><Database Name="test1" Class="zayavkirabotnikDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-S1G2RH08\SQLEXPRESS;Initial Catalog=test1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="test1ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.rabotniki" Member="rabotniki1">
    <Type Name="rabotniki1">
      <Column Name="ТабельныйНомер" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ФИО" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="НомерТелефона" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Цех" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.spisokzayavok1" Member="spisokzayavok12">
    <Type Name="spisokzayavok12">
      <Column Name="НоваяЗаявка" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="НомерЗаявки" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ДатаЗаявки" Type="System.DateTime" DbType="SmallDateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ФИО" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ТабельныйНомер" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="НомерТелефона" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ТипЗаявки" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ОписаниеЗаявки" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="СтатусЗаявки" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ОписаниеСтатуса" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Мастер" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>